### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by JoshPaterson** [brandon-rhodes/assay#5]
I've been using assay in linux on a virtual machine, and I really like it!

I know making it support windows is not at all trivial, but in case someday you decide that's something you want to do I'll put the error I get when trying to run it here:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\assay-script.py", line 11, in <module>
    load_entry_point('assay==0.0', 'console_scripts', 'assay')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\assay\command.py", line 8, in <module>
    from . import monitor, unix
  File "C:\ProgramData\Anaconda3\lib\site-packages\assay\monitor.py", line 7, in <module>
    from . import unix
  File "C:\ProgramData\Anaconda3\lib\site-packages\assay\unix.py", line 4, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

Thanks!

**Comment by brandon-rhodes** [comment]
Thanks for opening the issue! We'll keep it open and hopefully someone soon will have time to tackle having Windows use alternate code in that code path.

**Comment by JoshPaterson** [comment]
I was able to run assay within windows by following these directions: 

https://www.betteridiot.tech/blog/pop/betterblog/2018/9/windows-10-linux-subsystem-for-python-developers

They describe how to enable the linux subsytem on windows, and then install an ubuntu terminal. Step 3 (installing an X server) is unneccesary since assay runs in the terminal.

**Comment by brandon-rhodes** [comment]
Wow, that's interesting! I didn't realize modern Windows could host Ubuntu "natively" where Ubuntu can then see all Windows drives. Thanks for pointing that out!

**Comment by JoshPaterson** [comment]
It works great, the Skyfield tests run about twice as fast as they did in a VM. For me it's a complete solution to this issue, though I think it's only possible in newer versions of Windows 10.
