### ISSUE TITLE
Testing skyfield 1.25 with current assay fails before starting to run tests on ARM and PowerPC

### ISSUE THREAD

**Issue by bnavigator** [brandon-rhodes/assay#8]
Different failure than #7:

https://build.opensuse.org/package/show/devel:languages:python:numeric/python-skyfield

```
[   52s] + /usr/bin/python3 -m assay --batch skyfield.tests
[   52s] Traceback (most recent call last):
[   52s]   File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
[   52s]     return _run_code(code, main_globals, None,
[   52s]   File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
[   52s]     exec(code, run_globals)
[   52s]   File "/home/abuild/rpmbuild/BUILD/assay-79f5d784a55d70f31b2c90b636910738cd74840e/assay/__main__.py", line 2, in <module>
[   52s]     main()
[   52s]   File "/home/abuild/rpmbuild/BUILD/assay-79f5d784a55d70f31b2c90b636910738cd74840e/assay/command.py", line 22, in main
[   52s]     monitor.main_loop(args.name, args.batch or not isatty)
[   52s]   File "/home/abuild/rpmbuild/BUILD/assay-79f5d784a55d70f31b2c90b636910738cd74840e/assay/monitor.py", line 62, in main_loop
[   52s]     next(runner)
[   52s]   File "/home/abuild/rpmbuild/BUILD/assay-79f5d784a55d70f31b2c90b636910738cd74840e/assay/monitor.py", line 114, in runner_coroutine
[   52s]     worker = workers[0]
[   52s] IndexError: list index out of range
[   52s] error: Bad exit status from /var/tmp/rpm-tmp.X4PdOv (%check)
```

[armv7l_log.txt](https://github.com/brandon-rhodes/assay/files/4975508/armv7l_log.txt) (32bit!, e.g. Raspi)
[aarch64_log.txt](https://github.com/brandon-rhodes/assay/files/4975509/aarch64_log.txt) (e.g. newer Raspi)
[ppc64_log.txt](https://github.com/brandon-rhodes/assay/files/4975507/ppc64_log.txt)

**Comment by bnavigator** [comment]
The determination of number of cpus fails in
https://github.com/brandon-rhodes/assay/blob/79f5d784a55d70f31b2c90b636910738cd74840e/assay/unix.py#L42-L47

armv7l:
```
[   84s] + cat /proc/cpuinfo
[   84s] processor	: 0
[   84s] model name	: ARMv7 Processor rev 1 (v7l)
[   84s] BogoMIPS	: 100.00
[   84s] Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
[   84s] CPU implementer	: 0x50
[   84s] CPU architecture: 7
[   84s] CPU variant	: 0x0
[   84s] CPU part	: 0x000
[   84s] CPU revision	: 1
[   84s] 
[   84s] processor	: 1
[   84s] model name	: ARMv7 Processor rev 1 (v7l)
[   84s] BogoMIPS	: 100.00
[   84s] Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
[   84s] CPU implementer	: 0x50
[   84s] CPU architecture: 7
[   84s] CPU variant	: 0x0
[   84s] CPU part	: 0x000
[   84s] CPU revision	: 1
[   84s] 
[   84s] processor	: 2
[   84s] model name	: ARMv7 Processor rev 1 (v7l)
[   84s] BogoMIPS	: 100.00
[   84s] Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
[   84s] CPU implementer	: 0x50
[   84s] CPU architecture: 7
[   84s] CPU variant	: 0x0
[   84s] CPU part	: 0x000
[   84s] CPU revision	: 1
[   84s] 
[   84s] processor	: 3
[   84s] model name	: ARMv7 Processor rev 1 (v7l)
[   84s] BogoMIPS	: 100.00
[   84s] Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
[   84s] CPU implementer	: 0x50
[   84s] CPU architecture: 7
[   84s] CPU variant	: 0x0
[   84s] CPU part	: 0x000
[   84s] CPU revision	: 1
[   84s] 
[   84s] Hardware	: Generic DT based system
[   84s] Revision	: 0000
[   84s] Serial		: 0000000000000000
```

```
[   51s] + cat /proc/cpuinfo
[   51s] processor	: 0
[   51s] BogoMIPS	: 400.00
[   51s] Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
[   51s] CPU implementer	: 0x43
[   51s] CPU architecture: 8
[   51s] CPU variant	: 0x1
[   51s] CPU part	: 0x0af
[   51s] CPU revision	: 1
[   51s] 
[   51s] processor	: 1
[   51s] BogoMIPS	: 400.00
[   51s] Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
[   51s] CPU implementer	: 0x43
[   51s] CPU architecture: 8
[   51s] CPU variant	: 0x1
[   51s] CPU part	: 0x0af
[   51s] CPU revision	: 1
[   51s] 
[   51s] processor	: 2
[   51s] BogoMIPS	: 400.00
[   51s] Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
[   51s] CPU implementer	: 0x43
[   51s] CPU architecture: 8
[   51s] CPU variant	: 0x1
[   51s] CPU part	: 0x0af
[   51s] CPU revision	: 1
[   51s] 
[   51s] processor	: 3
[   51s] BogoMIPS	: 400.00
[   51s] Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
[   51s] CPU implementer	: 0x43
[   51s] CPU architecture: 8
[   51s] CPU variant	: 0x1
[   51s] CPU part	: 0x0af
[   51s] CPU revision	: 1
```

ppc64:
 ```
[   54s] processor	: 0
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 1
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 2
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 3
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 4
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 5
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 6
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] processor	: 7
[   54s] cpu		: POWER8 (architected), altivec supported
[   54s] clock		: 3425.000000MHz
[   54s] revision	: 2.1 (pvr 004b 0201)
[   54s] 
[   54s] timebase	: 512000000
[   54s] platform	: pSeries
[   54s] model		: IBM pSeries (emulated by qemu)
[   54s] machine		: CHRP IBM pSeries (emulated by qemu)
[   54s] MMU		: Hash
```


Any particular reason, the function looks for `^bogomips` and not for `^processor`?

**Comment by bnavigator** [comment]
Python >=3.4 has [os.cpu_count](https://docs.python.org/3/library/os.html#os.cpu_count) and there is [multiprocessing.cpu_count](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.cpu_count), too

**Comment by brandon-rhodes** [comment]
> Any particular reason, the function looks for ^bogomips and not for ^processor?

Because the first ^processor does not begin with a newline, and so wouldn't get matched by the pattern.

I'm not clear on why it's failing, when I see the word "processor" on those systems too?

In any case, I'll have it default to 2 if 0 comes back from that test!

**Comment by bnavigator** [comment]
> > Any particular reason, the function looks for ^bogomips and not for ^processor?
> 
> Because the first ^processor does not begin with a newline, and so wouldn't get matched by the pattern.

Then use regex or prepend the cpuinfo string with another newline before counting. Or read the lines one by one and count the lines beginning with processor. 

```python-console
>>> with open('/proc/cpuinfo') as f:
...     ("\n" + f.read()).count("\nprocessor")
... 
4
>>> with open('/proc/cpuinfo') as f:
...     len([l for l in f if l.startswith("processor")])
... 
4
>>> n=0
>>> with open('/proc/cpuinfo') as f:
...     for l in f:
...         n += int(l.startswith("processor"))
... 
>>> n
4
>>> with open('/proc/cpuinfo') as f:
...     len(re.findall('^processor', f.read(), re.MULTILINE))
... 
4
```

So many opportunities. lowercase 'bogomips' is not a good choice.
 

> I'm not clear on why it's failing, when I see the word "processor" on those systems too?

Because you don't look for "processor"??

<hr />

```python
def cpu_count(): 
    """Return the number of CPUs on the system.""" 
    try:
        return os.cpu_count()
    except AttributeError:
        pass
    n = 0
    try:
         with open('/proc/cpuinfo') as f:
             for l in f:
                 n += int(l.startswith("processor"))
    except (IOError, OSError):
        pass
    return n if n > 0 else 2

**Comment by brandon-rhodes** [comment]
> lowercase 'bogomips'

I see the case difference now! Thanks.

**Comment by bnavigator** [comment]
And no 'bogomips' of any case on PowerPC!

**Comment by brandon-rhodes** [comment]
I have switched to an RE, per your recommendation. Thanks!
